# Generated by Django 5.2.7 on 2026-01-09 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('documents', '0005_group_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
